apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  ports:
    - port: 3306
      targetPort: mysql-db-port
      protocol: TCP
      nodePort: 31006
  selector:
    app: mysql-db
  type: NodePort